apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ realm_name }}
  namespace: {{ rhbk_ns | d('sso-rhbk', true) }}
  labels:
    app: sso
spec:
  keycloakCRName: rhsso
  realm:
{% if sso_relamimport_yaml is defined and sso_relamimport_yaml != '' %}
{{ lookup("file", sso_relamimport_yaml) | indent(width=4, first=True) }}
{% endif %}
